// sidebars.ts
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: Record<string, SidebarsConfig> = {
  api: {
    apiSidebar: [{type: 'autogenerated', dirName: '.'}],
  },
  compliance: {
    complianceSidebar: [{type: 'autogenerated', dirName: '.'}],
  },
  gettingStarted: {
    gettingStartedSidebar: [{type: 'autogenerated', dirName: '.'}],
  },
  status: {
    statusSidebar: [{type: 'autogenerated', dirName: '.'}],
  },
};

export default sidebars;
